Integrated condition variable into scheduler and changed command queue implementation
TUM-LRR/era-gp-sim pull request #219
Opened 2016-12-26 00:00 UTC by janschopohl

closes #218

2016-12-26 11:34 UTC, janschopohl commented
Temporarily closed as I had a new idea how to improve this by syncing the ui.

2016-12-31 02:12 UTC, goldsborough requested changes

2016-12-31 02:12 UTC, goldsborough commented on source/core/scheduler.cpp
> +    while (_taskQueue.empty()) {
Couldn't we use the predicate feature of the condition variable here?
```
_conditionVariable.wait(lock, [&_taskQueue]{ return !_taskQueue.empty(); })
```

2016-12-31 02:12 UTC, goldsborough commented on source/core/scheduler.cpp
> +    if (!lock) lock.lock();
You make these checks here (and in other places), but one of the properties of the condition variable is that the mutex is reacquired upon wakeup. As such I think this check is unnecessary?

2016-12-31 02:12 UTC, goldsborough commented on tests/core/project-test.cpp
> +        [this]() { this->projectModule.guiReady(); });
There's special syntax that let's you write a lambda without arguments simply as `[...]{...}` (no parantheses)

2016-12-31 12:52 UTC, merged